### ISSUE TITLE
Introudce venv in the CI

### ISSUE THREAD

**Issue by tigercosmos** [solvcon/solvcon#416] opened 2024-08-21 04:28 UTC
Currently we use `--break-system-packages`  to avoid the pip install error since Python 3.12. However, it's hacky and not easy to maintain. Consider to introduce "venv" in the CI to avoid the pip issue.
https://github.com/solvcon/modmesh/blob/350ce86cbf58f4ebabe016c44f5f00a625da48a7/.github/workflows/devbuild.yml#L314-L318

**Comment by yungyuc** [comment] 2024-08-21 09:10
Introducing a virtual environment is not a good idea.  I intend to avoid virtual environments in the modmesh tool chain.  Dependencies for the HPC tool should be built from source as much as possible.  In this regard, pip is a necessary evil before we work out a better solution with [devenv](https://github.com/solvcon/devenv).

A virtual environment is bad because it is hard to reproduce an issue in itself.  If using conda or venv, we will need to deal with both the virtual environment and pip.  That is additional complexity.  A rule of thumb to use a virtual environment in production is that the users can productively troubleshoot it like their own code.  (Being a contributor to the virtual environment or a paying customer meets the condition.)  That is a commitment infeasible for modmesh at the moment.

We should not introduce a virtual environment unless we have to.  Remove `--break-system-packages` from pip is not a must-have.  I will mark this issue as won't fix and close it.  But we can discuss if needed.

**Closed as completed by yungyuc** 2024-08-21 09:10 UTC
Labels: wontfix

**Comment by tigercosmos** [comment] 2024-08-21 09:18
I see. Thanks for the clarification.
